"use strict";

// tests for listAll
// Generated by serverless-jest-plugin
const mod = require("./../src/functions/starships/listAll/handler");

const jestPlugin = require("serverless-jest-plugin");
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "main" });

describe("Testing... /api/starships/", () => {
  beforeAll((done) => {
    // lambdaWrapper.init(); // Run the deployed lambda
    done();
  });

  it("Debe responder un objeto con el parametro data y tener un codigo de estado 200", () => {
    return wrapped.run().then((response) => {
      const { statusCode } = response;
      const { data } = JSON.parse(response.body);

      // la respuesta es un objecto
      expect(typeof response).toBe("object");

      // tiene el parametro data y es un array
      expect(data).toEqual(expect.any(Array));

      // tiene el código de estado 200
      expect(statusCode).toBe(200);
    });
  });
});
