"use strict";

// tests for searchById
// Generated by serverless-jest-plugin
const jestPlugin = require("serverless-jest-plugin");
const lambdaWrapper = jestPlugin.lambdaWrapper;
const mod = require("./../src/functions/starships/searchById/handler");
const wrapped = lambdaWrapper.wrap(mod, { handler: "main" });

describe("Testing... searchById", () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  const _falseEvent = (id) => {
    return {
      pathParameters: {
        id,
      },
    };
  };

  const _context = {
    awsRequestId: "99999-b",
  };

  test("Buscando el ID: 5", () => {
    return wrapped.run(_falseEvent("5"), _context).then((response) => {
      const { statusCode } = response;
      const { data } = JSON.parse(response.body);
      expect(statusCode).toBe(200);
      expect(data.nombre).toBe("Sentinel-class landing craft");
    });
  });

  test("Buscando un ID que no existe en SWAPI, EJ: 0", () => {
    return wrapped.run(_falseEvent("0"), _context).then((response) => {
      const { statusCode } = response;
      const { error } = JSON.parse(response.body);
      expect(statusCode).toBe(200);
      expect(error).toBe("not found in Dynamo or SWAPI");
    });
  });
});
